
#define FOXPFCLASS_NODE		0x1000

#define FOXPFCLASS_GEODE		0x2000
#define FOXPFTYPE_GEODE		(100 | FOXPFCLASS_GEODE | FOXPFCLASS_NODE)

/* foxpfGroup types */
#define FOXPFCLASS_GROUP		0x4000
#define FOXPFTYPE_GROUP		(100 | FOXPFCLASS_GROUP | FOXPFCLASS_NODE)
#define FOXPFTYPE_SWITCH		(101 | FOXPFCLASS_GROUP | FOXPFCLASS_NODE)
#define FOXPFTYPE_LOD			(102 | FOXPFCLASS_GROUP | FOXPFCLASS_NODE)


#define FOXPFCLASS_SCS		0x8000
#define FOXPFTYPE_SCS		(100 |FOXPFCLASS_SCS | FOXPFCLASS_GROUP | FOXPFCLASS_NODE)
#define FOXPFTYPE_DCS		(101 |FOXPFCLASS_SCS | FOXPFCLASS_GROUP | FOXPFCLASS_NODE)
#define WOLFFOXPFTYPE_BBOARD	(102 |FOXPFCLASS_SCS | FOXPFCLASS_GROUP | FOXPFCLASS_NODE)


#define FOXPFGS_POINTS	    	0
#define FOXPFGS_LINES	    	1
#define FOXPFGS_LINESTRIPS	    	2	
#define FOXPFGS_TRIS	    	3
#define FOXPFGS_QUADS	    	4
#define FOXPFGS_TRISTRIPS	    	5
#define FOXPFGS_FLAT_LINESTRIPS	6
#define FOXPFGS_FLAT_TRISTRIPS	7

#define FOXPFGS_COORD3 0
#define FOXPFGS_TEXCOORD2 1


#define FOXNODE_FLAG_DCSDIRTY1			0x0001
#define FOXNODE_FLAG_SCSDIRTY			0x0001
#define FOXNODE_FLAG_DCSDIRTY2			0x0002
#define FOXNODE_FLAG_DCSDIRTY			0x0003

#define FOXNODE_FLAG_NO_INTERSECTION	0x0004	/**** don't traverse this FOXNODE for intersections ****/
#define FOXNODE_FLAG_DCS_NOROT          0x0008  /**** An SCS or DCS with no rotation (or scaling) components ****/
#define FOXNODE_FLAG_DCS_PIVOT			0x0010  /***  A DCS (never an SCS) that has a valid pivot ***/
#define FOXNODE_FLAG_INSTANCED			0x0020




#define FOXPFTEX_LUT_MASK   0x03
#define FOXPFTEX_LUT_NONE   0x00
#define FOXPFTEX_LUT_RGBA16 0x01
#define FOXPFTEX_LUT_IA16   0x02
#define FOXPFTEX_LUT_INVAL  0x03

#define FOXPFTEX_DETAIL_MASK    0x0C
#define FOXPFTEX_DETAIL_CLAMP   0x00
#define FOXPFTEX_DETAIL_SHARPEN 0x04
#define FOXPFTEX_DETAIL_DETAIL  0x08
#define FOXPFTEX_DETAIL_INVAL   0x0C

#define FOXPFTEX_FILTER_MASK    0x30
#define FOXPFTEX_FILTER_BILERP  0x00
#define FOXPFTEX_FILTER_POINT   0x10
#define FOXPFTEX_FILTER_AVERAGE 0x20
#define FOXPFTEX_FILTER_INVAL   0x30

#define FOXPFTEX_LOD_MASK       0xC0
#define FOXPFTEX_LOD_TILE       0x00
#define FOXPFTEX_LOD_LOD        0x40
#define FOXPFTEX_LOD_INVAL      0xC0


#define FOXPFTEX_TILED     	0x00000100


#define FOXPFML_R 0
#define FOXPFML_G 1
#define FOXPFML_B 2
#define FOXPFML_A 3
#define FOXPFML_M 0	/**** notice that these overlap the colors!!! PrimColor must usr 2+FOXPFML_R, etc. ****/
#define FOXPFML_L 1


#define FOXPFML_PRIMCOLOR 0x00000001
#define FOXPFML_ENVCOLOR 0x00000002
#define FOXPFML_FOGCOLOR 0x00000004
#define FOXPFML_BLENDCOLOR 0x00000008



#define FOXPFGSTATE_LIGHTED			0x0001
#define FOXPFGSTATE_FOGGED				0x0002
#define FOXPFGSTATE_SMOOTH_SHADED		0x0004
#define FOXPFGSTATE_BACKFACE_ELIM		0x0008
#define FOXPFGSTATE_TEXGEN_REFLECT		0x0010
#define FOXPFGSTATE_TEXGEN_LINEAR		0x0020
#define FOXPFGSTATE_FRONTFACE_ELIM		0x0040

#define FOXPFGSTATE_TILED_TEXTURE		0x4000	/* used instead of dicing up tiled textures */
#define FOXPFGSTATE_TEXTURESCROLL		0x8000

#define FOXPFSTATE_CULLFACE  0x01  /* For use with foxpfGetGStateMode */
#define FOXPFSTATE_TEXTURE   0x02

#define FOXPFCF_OFF   0x00
#define FOXPFCF_BACK  0x01
#define FOXPFCF_FRONT 0x02
#define FOXPFCF_BOTH  0x03



#define WOLFFOXPFBB_ROT		0
#define WOLFFOXPFBB_TRANS	1

#define WOLFFOXPFBB_ROT_FREE	0
#define WOLFFOXPFBB_ROT_AXIAL	1
#define WOLFFOXPFBB_ROT_POINT_EYE	2
#define WOLFFOXPFBB_ROT_POINT_WORLD	3

#define WOLFFOXPFBB_TRANS_FREE		0
#define WOLFFOXPFBB_TRANS_FIXED	1


